[package]
name = "allerta_meteo"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = { version = "0.27", features = ["macros", "palette", "unstable-widget-ref", "serde"] }
crossterm = "0.27"
fakeit = "1.2"
itertools = "0.13"
unicode-width = "0.1"
reqwest = { version = "0.12", features = ["json", "blocking"] }
serde = "1"
serde_json = "1"
serde_with = "3.9"
chrono = { version = "0.4", features = ["serde"] }
